### ISSUE TITLE
No write permission for file: f.obj

### ISSUE THREAD

**Issue by godeye** [faerietree/freecad_convert#1]
>  python convert.py f.stp f.obj
FreeCAD 0.14, Libs: 0.14R3702 (Git)
('.stp', ' -> ', '.obj')
('Opening parametric file: ', 'f.stp')
      ...    Step File Reading : f.stp
      ...    STEP File   Read    ...
Elapsed time: 0 Hours 0 Minutes 0.049828 Seconds
CPU user time: 0.04 seconds
CPU system time: 0.01 seconds
      ... Step File loaded  ...
Elapsed time: 0 Hours 0 Minutes 0.079124 Seconds
CPU user time: 0.07 seconds
CPU system time: 0.01 seconds
   57128 records (entities,sub-lists,scopes), 177857 parameters
Reading STEP file......
('Exporting to mesh file: ', 'f.obj')
Exception (Thu Nov 30 10:52:23 2017): No write permission for file: f.obj
Traceback (most recent call last):
  File "convert.py", line 112, in <module>
    main()
  File "convert.py", line 89, in main
    Mesh.export([o], out_f)
Exception: FreeCAD exception thrown (No write permission for file: f.obj)

**how to solve the problem**

**Comment by faerietree** [comment]
Have writing permissions in the directory?

Else changing directory or maybe running as root helps (sudo python freecad_convert.py ...)

**Comment by godeye** [comment]
i have login with root.
